"""update relationships

Revision ID: 1818c843b51b
Revises: 8f94d4295125
Create Date: 2021-08-22 22:07:10.972868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1818c843b51b'
down_revision = '8f94d4295125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('parent_section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sections', 'sections', ['parent_section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sections', type_='foreignkey')
    op.drop_column('sections', 'parent_section_id')
    # ### end Alembic commands ###
