"""Change relation between article and sections

Revision ID: 58cedf22adfb
Revises: a1d03f0e374e
Create Date: 2021-09-06 22:22:01.291331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cedf22adfb'
down_revision = 'a1d03f0e374e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sectionArticles')
    op.add_column('articles', sa.Column('section_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'sections', ['section_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'section_id')
    op.create_table('sectionArticles',
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='sectionArticles_article_id_fkey'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='sectionArticles_section_id_fkey')
    )
    # ### end Alembic commands ###
