"""update relationships

Revision ID: 76f4329f1edc
Revises: 449595adb514
Create Date: 2021-08-22 22:14:39.296741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f4329f1edc'
down_revision = '449595adb514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'article_id')
    # ### end Alembic commands ###
