"""update relationships

Revision ID: 8f94d4295125
Revises: eacd4bab119b
Create Date: 2021-08-22 22:01:35.662276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f94d4295125'
down_revision = 'eacd4bab119b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectionArticles',
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], )
    )
    op.create_table('tagArticles',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_table('userModerators',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_index('ix_moderators_id', table_name='moderators')
    op.drop_table('moderators')
    op.drop_table('articleTag')
    op.drop_constraint('articles_section_id_fkey', 'articles', type_='foreignkey')
    op.drop_column('articles', 'section_id')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_responses_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'responses_id')
    op.drop_column('comments', 'user_id')
    op.drop_constraint('sections_subsection_id_fkey', 'sections', type_='foreignkey')
    op.drop_column('sections', 'subsection_id')
    op.drop_constraint('tags_article_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'article_id')
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('tags', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_article_id_fkey', 'tags', 'articles', ['article_id'], ['id'])
    op.add_column('sections', sa.Column('subsection_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('sections_subsection_id_fkey', 'sections', 'sections', ['subsection_id'], ['id'])
    op.add_column('comments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('responses_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_responses_id_fkey', 'comments', 'comments', ['responses_id'], ['id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.add_column('articles', sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('articles_section_id_fkey', 'articles', 'sections', ['section_id'], ['id'])
    op.create_table('articleTag',
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='articleTag_article_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='articleTag_tag_id_fkey')
    )
    op.create_table('moderators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='moderators_section_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='moderators_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='moderators_pkey')
    )
    op.create_index('ix_moderators_id', 'moderators', ['id'], unique=False)
    op.drop_table('userModerators')
    op.drop_table('tagArticles')
    op.drop_table('sectionArticles')
    # ### end Alembic commands ###
