"""Propper user comment relation

Revision ID: 906eeddb5066
Revises: 58cedf22adfb
Create Date: 2021-09-06 23:01:34.810111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906eeddb5066'
down_revision = '58cedf22adfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'author_id')
    # ### end Alembic commands ###
