"""fix typo

Revision ID: 9fb65b3b335f
Revises: 76f4329f1edc
Create Date: 2021-08-22 22:52:02.553737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb65b3b335f'
down_revision = '76f4329f1edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
