"""Add relationship to section

Revision ID: eacd4bab119b
Revises: 49bba1d21269
Create Date: 2021-08-22 20:21:10.510373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacd4bab119b'
down_revision = '49bba1d21269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
